FROM apache/spark:3.5.0

USER root

RUN apt-get update && \
  apt-get install -y python3 python3-pip && \
  pip3 install --upgrade pip

RUN pip3 install pyspark==3.5.0 kafka-python numpy pandas 

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]

# run prediction script directly
# CMD ["python3", "-m", "online.prediction"]
